auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title
gems:
  - jekyll-sitemap

title: Vien's island | Sun will shine on the horizon.
url: http://daiweiyang.com
feed: /atom.xml
author_info: <a href="http://daiweiyang.com">Vien's island | Sun will shine on the horizon.</a>
name: 戴维扬
email: jacob.seu.cose@gmail.com
