auto: true

markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
paginate: 8
permalink: /:title
gems:
  - jekyll-sitemap

title: Vien's Island | Sun will shine on the horizon.
url: http://daiweiyang.com
feed: /atom.xml
author_info: <a href="http://daiweiyang.com">Vien's Island | Sun will shine on the horizon.</a>
name: 戴维扬
email: jacob.seu.cose@gmail.com
